steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: "sh"
    args:
      - "-c"
      - |
        ENVIRONMENT=$$(printf '%s' "$BRANCH_NAME" | sed 's/-.*//' | sed 's/[0-9]//g')
        gsutil cp gs://attach-containers-secrets/$$ENVIRONMENT-npmrc .npmrc
        # TODO: fetch SVN secret
  - name: "node:9-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        chmod +x ./hooks/build.sh
        ./hooks/build.sh $BRANCH_NAME
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$COMMIT_SHA",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/$REPO_NAME"]
tags: ["$BRANCH_NAME-$COMMIT_SHA"]
