steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://attach-containers-secrets/id_rsa.enc", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=/root/.ssh/id_rsa
      - --location=global
      - --keyring=attach-kubernetes
      - --key=github-key
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ssh-keyscan -t rsa github.com > known_hosts
        chmod 600 /root/.ssh/id_rsa
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_rsa
        EOF
        mv known_hosts /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ENVIRONMENT=$$(printf '%s' "$BRANCH_NAME" | sed 's/-.*//' | sed 's/[0-9]//g')
        git clone -b "$${ENVIRONMENT}" git@github.com:attach-live/attach-kubernetes
    volumes:
      - name: "ssh"
        path: /root/.ssh
  - name: "node:10.15.3-stretch"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        chmod +x ./attach-kubernetes/scripts/build-env.sh
        ./attach-kubernetes/scripts/build-env.sh $REPO_NAME $BRANCH_NAME
        set -a
        . ./variables.env
        set +a
        chmod +x ./hooks/build.sh
        ./hooks/build.sh $BRANCH_NAME
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$COMMIT_SHA",
        ".",
      ]
images: ["gcr.io/$PROJECT_ID/$REPO_NAME"]
tags: ["$BRANCH_NAME-$COMMIT_SHA"]
